# Generated by Django 4.2.1 on 2024-04-23 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nizhnii', '0002_groups_interestingplacesmodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestingplacesmodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='nizhnii.groups'),
        ),
    ]
