# Generated by Django 4.2.1 on 2024-04-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizhnii', '0004_groups_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='icon',
            field=models.CharField(max_length=30),
        ),
    ]
